batch_size: 256
checkpoint_path: lightning_logs/checkpoints/convnet3d-large-classifier/convnet3d-large-classifier-epoch=78-val_loss=0.48-val_f1=0.65.ckpt
class_weights: [0.87, 0.3, 0.7]
data_path: data 
processing: P07
dropout: 0.001
freeze_block: null
lr: 1e-3
max_epochs: 70
model_name: convnet3d-large-classifier
num_conv_blocks: 4
num_workers: 8
optimizer_alg: lion
precision: high
scheduler_gamma: 0.5
scheduler_step_size: 10
weight_decay: 0.0005