model_name: convnet3d-from-checkpoint
dropout: 0.001
lr: 1e-5
scheduler_step_size: null
scheduler_gamma: null
weight_decay: 0.0005
optimizer_alg: lion
class_weights: [0.85,0.4,0.7]
freeze_block: null
batch_size: 256
num_workers: 8
max_epochs: 200
data_path: data/new-norm
precision: high
checkpoint_path: lightning_logs/checkpoints/convnet3d-balance/convnet3d-balance-epoch=51-val_loss=0.42-val_f1=0.85.ckpt