batch_size: 256
checkpoint_path: lightning_logs/checkpoints/convnet-regression/convnet-regression-epoch=13-val_loss=0.08-val_f1=0.36.ckpt
class_weights: [0.87, 0.3, 0.7]
data_path: data/original
dropout: 0.0001
freeze_block: null
lr: 1e-4
max_epochs: 100
model_name: convnet-regression
num_conv_blocks: 4
num_workers: 8
optimizer_alg: adam
precision: high
scheduler_gamma: 0.5
scheduler_step_size: 5
weight_decay: 0.00005
params: [0.4, 0.6]