batch_size: 64
checkpoint_path: lightning_logs/checkpoints/resnet/resnet/resnet-epoch=00-val_loss=0.49-val_f1=0.52.ckpt
class_weights: [0.87, 0.3, 0.7]
data_path: data/original
model_depth: 18
lr: 1e-7
max_epochs: 10
model_name: resnet
num_workers: 8
optimizer_alg: adam
precision: high
scheduler_gamma: 0.5
scheduler_step_size: 20
weight_decay: 0.0005
freeze: null