batch_size: 256
checkpoint_path: null
class_weights: [0.87, 0.3, 0.7]
data_path: data/new-norm
model_depth: 18
lr: 1e-3
max_epochs: 70
model_name: resnet
num_workers: 8
optimizer_alg: adam
precision: high
scheduler_gamma: 0.5
scheduler_step_size: 20
weight_decay: 0.0005