batch_size: 64
checkpoint_path: lightning_logs/checkpoints/vit-age-gender/vit-age-gender-P03-epoch=74-val_loss=0.40-val_recall=0.74.ckpt
class_weights: [0.87,0.3,0.72]
data_path: data
dropout: 0
lr: 1e-6
max_epochs: 15
model_name: vit-age-gender-P03-prune
num_workers: 8
optimizer_alg: adam
precision: high
scheduler_gamma: 0.7
scheduler_step_size: 30
weight_decay: 0
image_patch_size: 25
frame_patch_size: 10
dim: 1024
depth: 6
heads: 16
dim_head: 128
mlp_dim: 2048
pool: cls
emb_dropout: 0
detail: Menor dropout
include_cudim: False
processing: P03
